version: '3.4'
services:
  wordpress:
    image: wordpress:5.8-php7.4-fpm-alpine
    depends_on:
      - database
    links:
      - database:mysql
    volumes:
      - wordpress_data:/var/www/html
      - ./plugins/wp-migrations:/var/www/html/wp-content/plugins/wp-migrations
      - ./themes/my-simple-theme:/var/www/html/wp-content/themes/my-simple-theme
    restart: always

  database:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - 3306:3306

  webserver:
    image: nginx:1.14-alpine
    restart: always
    links:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./docker/nginx/website.conf:/etc/nginx/conf.d/default.conf:ro
      - ./plugins/wp-migrations:/var/www/html/wp-content/plugins/wp-migrations
      - ./themes/my-simple-theme:/var/www/html/wp-content/themes/my-simple-theme
    ports:
      - ${WEBSERVER_PORT}:80

  toolbox:
    image: michaelperrin/wordpress-toolbox
    volumes:
      - wordpress_data:/wordpress
      - ./plugins/wp-migrations:/wordpress/wp-content/plugins/wp-migrations
      - ./themes/my-simple-theme:/wordpress/wp-content/themes/my-simple-theme
      - ./migrations:/wordpress/wp-content/migrations
      - ./Makefile:/scripts/Makefile
    depends_on:
      - database
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USERNAME}
      WORDPRESS_DOMAIN_NAME: ${WORDPRESS_DOMAIN_NAME}
      WORDPRESS_WEBSITE_URL: ${WORDPRESS_WEBSITE_URL}
      WORDPRESS_LOCALE: en_US
      WORDPRESS_WEBSITE_POST_URL_STRUCTURE: "/%year%/%monthnum%/%day%/%postname%/"
      WORDPRESS_WEBSITE_TITLE: "My beautiful website"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - 8082:80

volumes:
  db_data: {}
  wordpress_data: {}
