version: '3.4'
services:
  wordpress:
    image: wordpress:5.2-php7.3-fpm-alpine
    links:
      - database:mysql
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    restart: always

  database:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - 3306:3306

  webserver:
    image: nginx:1.14-alpine
    links:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./docker/nginx/website.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wp-content:/var/www/html/wp-content
    ports:
      - ${WEBSERVER_PORT}:80

  toolbox:
    build: ./docker/wp-toolbox/
    volumes:
      - wordpress_data:/wordpress
      - ./wp-content:/wordpress/wp-content
      - ./docker/wp-toolbox/Makefile:/wordpress/Makefile
    depends_on:
      - database
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USERNAME}
      WORDPRESS_DOMAIN_NAME: ${WORDPRESS_DOMAIN_NAME}
      WORDPRESS_WEBSITE_URL: ${WORDPRESS_WEBSITE_URL}
      WORDPRESS_LOCALE: en_US
      WORDPRESS_WEBSITE_POST_URL_STRUCTURE: "/%year%/%monthnum%/%day%/%postname%/"
      WORDPRESS_WEBSITE_TITLE: "My beautiful website"

volumes:
  db_data: {}
  wordpress_data: {}
